//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HexEdit.rc
//
#define VERSION_MINOR                   0
#define IDC_PADDINGB                    1
#define IDC_ADVANCED                    1
#define IDC_FONTLIST                    1
#define IDS_HEXTYPES                    1
#define IDC_SIZELIST                    2
#define IDS_STRING2                     2
#define VERSION_MAJOR                   2
#define IDOK2                           2
#define IDCANCEL2                       3
#define IDC_ITEMLIST                    3
#define IDC_FGCOLCOMBO                  4
#define VERSION_BUILD                   4
#define IDC_BUTTON2                     5
#define IDC_BGCOLCOMBO                  6
#define IDC_BUTTON3                     7
#define IDC_BOLD                        11
#define VERSION_BUILD_COUNT             16
#define IDI_APP                         100
#define IDR_MENU1                       101
#define IDB_BITMAP1                     103
#define IDD_SEARCH                      104
#define IDD_FINDHEX                     105
#define IDD_FINDASC                     106
#define IDD_FINDCUST                    107
#define IDD_FINDNUM                     107
#define IDD_FINDREPLACE                 108
#define IDD_PASTESPECIAL                109
#define IDD_SEARCHBAR                   110
#define IDB_BITMAP2                     111
#define IDB_BITMAP3                     112
#define IDD_SELECTRANGE                 113
#define IDB_BITMAP4                     113
#define IDB_BITMAP5                     114
#define IDB_PIN_BITMAP                  116
#define IDR_ACCELERATOR1                117
#define IDD_DIALOG1                     117
#define IDB_BITMAP6                     118
#define IDD_PROPERTY_LAYOUT             119
#define IDB_BITMAP7                     119
#define IDD_PROPERTY_DISPLAY            120
#define IDR_SEARCHBAR_FINDTYPE          120
#define IDD_PROPERTY_MISC               121
#define IDI_ICON1                       122
#define IDI_ICON2                       123
#define IDI_ICON3                       124
#define IDD_EXPORTEXTEND                125
#define IDD_PROGRESS                    126
#define IDD_INSERT                      127
#define IDD_OPENEXTEND                  128
#define IDD_SAVEEXTEND                  129
#define IDD_ABOUT                       130
#define IDD_MODIFY                      131
#define IDD_TRANSFORM                   131
#define IDB_BITMAP9                     132
#define IDR_HEXCONTEXT                  133
#define IDD_HIGHLIGHT                   134
#define IDD_IMPORTEXTEND                135
#define IDD_GOTOBOX                     136
#define IDD_GOTO                        136
#define IDB_BITMAP10                    136
#define IDD_PROPERTY_FONT               137
#define IDI_ICON4                       138
#define IDD_DIALOG2                     139
#define IDD_GOTO2                       139
#define IDI_ICON5                       140
#define IDD_PROPERTIES                  141
#define IDB_BITMAP11                    141
#define IDR_TYPECONTEXT                 142
#define IDD_TYPEDLG                     143
#define IDB_BITMAP12                    144
#define IDD_PROPERTY_TYPE               145
#define IDB_DROPLIST_BITMAP             146
#define IDB_BITMAP13                    147
#define IDR_MENU2                       148
#define IDR_MENU3                       149
#define IDR_DUMMYCOMMANDS               150
#define IDR_MENU4                       151
#define IDB_BITMAP14                    152
#define IDD_GENCRC                      153
#define IDD_CHECKSUM                    153
#define IDD_STRINGS                     154
#define IDD_COMPARE                     155
#define IDD_DIALOG3                     156
#define IDI_ICON6                       157
#define IDB_BITMAP15                    159
#define IDB_PNG4                        164
#define IDB_PNG6                        166
#define IDB_SELARROW                    167
#define IDB_SELBOX                      168
#define IDB_SELARROW2                   169
#define IDD_PRINT                       170
#define IDB_PNG2                        170
#define IDB_SELBOX2                     170
#define IDR_RT_MANIFEST1                171
#define IDD_PASTEFROMEXTEND             172
#define IDD_REVERSE                     173
#define IDD_COPYAS                      174
#define IDD_PROPERTY_FILES              176
#define IDD_COPYTOEXTEND                188
#define IDC_EDIT1                       1000
#define IDC_TAB1                        1000
#define IDC_ANNOTATION                  1000
#define IDC_EDIT2                       1001
#define IDC_COMBO1                      1001
#define IDC_FILEPATH                    1001
#define IDC_EDIT3                       1002
#define IDC_COMBO4                      1002
#define IDC_FILESIZE                    1002
#define IDC_EDIT4                       1003
#define IDC_COMBO3                      1003
#define IDC_OFFSET                      1003
#define IDC_COMBO2                      1004
#define IDC_EDIT5                       1004
#define IDC_LENGTH                      1004
#define IDC_FONTSIZE                    1005
#define IDC_TOOLBAR1                    1005
#define IDC_TOOLBAR2                    1006
#define IDC_SCOPE_CURSOR                1006
#define IDC_SCOPE_SEL                   1007
#define IDC_SEARCH_UNICODE              1009
#define IDC_SEARCH_ENDIAN               1009
#define IDC_MATCHCASE                   1010
#define IDC_CHECK2                      1011
#define IDC_SEARCHBACK                  1012
#define IDC_COLOURLIST                  1013
#define IDC_SWAPBYTES                   1013
#define IDC_VIEWONLY                    1014
#define IDC_KEEPVISIBLE                 1014
#define IDC_CHECK1                      1015
#define IDC_USEADDRESS                  1015
#define IDC_CHECK3                      1016
#define IDC_HEADER2                     1016
#define IDC_ABOUT_ICON                  1016
#define IDC_RADIO1                      1017
#define IDC_ABOUT_APPNAME               1017
#define IDC_RADIO2                      1018
#define IDC_ABOUT_URL                   1018
#define IDC_RADIO3                      1019
#define IDC_EDIT_PREVIEW                1019
#define IDC_SPIN1                       1020
#define IDC_SPLIT1                      1020
#define IDC_SPIN2                       1021
#define IDC_BOOKMARKS                   1021
#define IDC_SPIN3                       1022
#define IDC_CHECK4                      1023
#define IDC_GROUP                       1023
#define IDC_DATALABEL                   1024
#define IDC_PROMPTSAVE                  1025
#define IDC_FILENAME                    1025
#define IDC_TYPEVIEWLOG                 1026
#define IDC_FILENAME2                   1026
#define IDC_WARNINSERT                  1028
#define IDC_NAME                        1029
#define IDC_BUTTON1                     1030
#define IDC_MODIFY_NUMBYTES             1032
#define IDC_MODIFY_OPERAND              1033
#define IDC_DEFREADONLY                 1034
#define IDC_ALGORITHM                   1034
#define IDC_DEFQUICKSAVE                1035
#define IDC_COMBO_DATATYPE              1035
#define IDC_DEFQUICKLOAD                1036
#define IDC_REPLACE                     1036
#define IDC_REPLACEALL                  1037
#define IDC_BROWSE1                     1037
#define IDC_BROWSE2                     1038
#define IDC_EXPORTFORMAT                1038
#define IDC_FILEICON                    1039
#define IDC_IMPORTFORMAT                1040
#define IDC_LIST1                       1041
#define IDC_ABOUT_AUTHOR                1042
#define IDC_HEXADDR                     1043
#define IDC_ABOUT_WEBSITE               1045
#define IDC_SYSLINK2                    1046
#define IDC_ABOUT_TERMS                 1046
#define IDC_STRING_TYPES                1047
#define IDC_CUSTOM1                     1048
#define IDC_HEXVIEW_PREVIEW             1048
#define IDC_DATETIMEPICKER1             1049
#define IDC_DATETIMEPICKER2             1050
#define IDC_DATETIMEPICKER3             1051
#define IDC_DATETIMEPICKER4             1052
#define IDC_DATETIMEPICKER5             1053
#define IDC_DATETIMEPICKER6             1054
#define IDC_DATATYPE                    1061
#define IDC_RANGETEXT                   1067
#define IDC_HEX                         1068
#define IDC_ENDIAN                      1069
#define IDC_GOTO_BEGIN                  1072
#define IDC_GOTO_RELATIVE               1073
#define IDC_GOTO_EOF                    1074
#define IDC_GOTO_HEX                    1075
#define IDC_GOTO_KEEPVISIBLE            1076
#define IDC_PREVIEW                     1079
#define IDC_PROPERTY_TOUCH              1080
#define IDC_ATTR_R                      1081
#define IDC_ATTR_H                      1082
#define IDC_ATTR_A                      1083
#define IDC_ATTR_S                      1084
#define IDC_LINE1                       1085
#define IDC_PASTEFROMLINK               1086
#define IDC_LINE2                       1086
#define IDC_ITEMWIDTH                   1087
#define IDC_PASTEFROM_INSMODE           1088
#define IDC_STATICSEL                   1089
#define IDC_ABOUT_LEGALSTR              1089
#define IDC_PASTEFROM_MASK              1090
#define IDC_DISPLAYMODS                 1091
#define IDC_CTRLCHARS                   1092
#define IDC_QUICKSAVE                   1094
#define IDC_ZEROBASEDADDRESS            1095
#define IDC_QUICKLOAD                   1095
#define IDC_MESSAGE                     1096
#define IDC_APPENDTOFILE                1096
#define IDC_ABORTICON                   1097
#define IDSTOP                          1098
#define IDC_READONLY                    1099
#define IDC_PRESERVEMODIFY              1101
#define IDC_DECADDR                     1102
#define IDC_EXPORTTYPE                  1103
#define IDC_LITTLEENDIAN                1104
#define IDC_GOTO_OFFSET                 1109
#define IDC_INSERT_NUMBYTES             1110
#define IDC_INSERT_FILLWITH             1111
#define IDC_PASTELIST                   1112
#define IDC_CLIPLIST                    1112
#define IDC_PASTEOVER                   1113
#define IDC_MASKSEL                     1114
#define IDC_FONTNAME                    1115
#define IDC_SHOWEXCHARS                 1116
#define IDC_BYTESPERROW                 1117
#define IDC_LEFTPAD                     1118
#define IDC_RIGHTPAD                    1119
#define IDC_REPLACESEL                  1121
#define IDC_STARTOVR                    1122
#define IDC_DRAGANDDROP                 1123
#define IDC_LINKDROPPED                 1124
#define IDC_ADDCONTEXT                  1125
#define IDC_REVERSE_OFFSET              1126
#define IDC_REVERSE_LENGTH              1127
#define IDC_SELLEN                      1128
#define IDC_SELEND                      1129
#define IDC_INSERT_DATATYPE             1130
#define IDC_MODIFY_DATATYPE             1130
#define IDC_FITTOWINDOW                 1131
#define IDC_MODIFY_OPERATION            1131
#define IDC_FITTOWINDOW2                1132
#define IDC_APPENDTO                    1133
#define IDC_ELEMENTLIST                 1135
#define IDM_FILE_EXIT                   40001
#define IDM_HELP_ABOUT                  40002
#define IDM_VIEW_HEX                    40003
#define IDM_VIEW_DEC                    40004
#define IDM_VIEW_OCT                    40005
#define IDM_VIEW_BIN                    40006
#define IDM_VIEW_FITWINDOW              40007
#define IDM_GROUP_BYTE                  40008
#define IDM_GROUP_WORD                  40009
#define IDM_GROUP_DWORD                 40010
#define IDM_VIEW_ADDRESS                40011
#define IDM_VIEW_LOWERCASE              40012
#define IDM_FILE_NEW                    40014
#define IDM_FILE_OPEN                   40015
#define IDM_FILE_SAVE                   40016
#define IDM_FILE_SAVEAS                 40017
#define IDM_FILE_REVERT                 40018
#define IDM_FILE_EXPORT                 40019
#define IDM_FILE_PRINT                  40020
#define IDM_FILE_PAGESETUP              40021
#define IDM_FILE_RECENT                 40022
#define IDM_EDIT_UNDO                   40023
#define IDM_EDIT_REDO                   40024
#define IDM_EDIT_CUT                    40025
#define IDM_EDIT_PASTEOVER              40025
#define IDM_EDIT_COPY                   40026
#define IDM_EDIT_PASTE                  40027
#define IDM_EDIT_COPYAS                 40028
#define IDM_EDIT_PASTESPECIAL           40029
#define IDM_EDIT_SELECTALL              40031
#define IDM_EDIT_SELECTRANGE            40032
#define IDM_EDIT_REVERSE                40033
#define IDM_EDIT_INSERT                 40033
#define IDM_EDIT_FILL                   40034
#define IDM_EDIT_COPYTO                 40035
#define IDM_EDIT_PASTEFROM              40036
#define IDM_SEARCH_FIND                 40037
#define IDM_SEARCH_REPLACE              40038
#define IDM_SEARCH_NEXT                 40039
#define IDM_SEARCH_PREV                 40040
#define IDM_SEARCH_GOTO                 40041
#define IDM_SEARCH_FINDNEXT             40041
#define IDM_SEARCH_REPEAT               40042
#define IDM_SEARCH_FINDPREV             40042
#define ID_TOOLS_OPTIONS                40043
#define IDM_TOOLS_OPTIONS               40043
#define IDM_TOOLS_CUSTOMIZE             40044
#define IDM_SEARCH_GOTOADDRESS          40044
#define IDM_TOOLS_CALCULATOR            40045
#define IDM_SEARCH_GOTOAGAIN            40045
#define IDM_TOOLS_TYPEVIEW              40046
#define IDM_TOOLS_TOOLBAR               40047
#define IDM_TOOLS_STATUSBAR             40048
#define IDM_TOOLS_SAVEONEXIT            40049
#define IDM_TOOLS_SAVENOW               40050
#define IDM_HELP_TOPICS                 40051
#define IDM_FILE_IMPORT                 40052
#define IDM_FILE_PROPERTIES             40053
#define IDM_FILE_CLOSE                  40054
#define IDM_SEARCHBAR_ASC               40055
#define IDM_SEARCHBAR_HEX               40056
#define IDM_SEARCHBAR_UINT8             40057
#define IDM_SEARCHBAR_INT8              40058
#define IDM_SEARCHBAR_UINT32            40059
#define IDM_SEARCHBAR_UNICODE           40060
#define IDM_TOOLS_OPERATION             40061
#define IDM_TOOLS_MODIFY                40061
#define IDM_TOOLS_TRANSFORM             40061
#define IDM_TOOLS_SEARCHBAR             40062
#define IDM_EDIT_DELETE                 40063
#define IDM_TYPEVIEW_NEW                40065
#define IDM_TYPEVIEW_DEFINE             40066
#define IDM_TYPEVIEW_DLG                40067
#define IDM_HIGHLIGHT_NEW               40069
#define IDM_HIGHLIGHT_DLG               40070
#define IDM_HIGHLIGHT_MANAGE            40071
#define IDM_HIGHLIGHT_REMOVE            40072
#define IDM_HIGHLIGHT_REMOVEALL         40073
#define IDM_EDIT_GOTO                   40074
#define IDM_RECENT1                     40075
#define IDM_RECENT2                     40076
#define IDM_RECENT3                     40077
#define IDM_RECENT4                     40078
#define IDM_RECENT5                     40079
#define IDM_RECENT6                     40080
#define IDM_RECENT7                     40081
#define IDM_RECENT8                     40082
#define IDM_TYPEVIEW_PROPERTIIES        40083
#define IDM_TYPEVIEW_CUT                40085
#define IDM_TYPEVIEW_HEX                40086
#define IDM_TYPEVIEW_OFFSET             40087
#define IDM_TYPEVIEW_EXPANDALL          40088
#define IDM_TYPEVIEW_COLLAPSALL         40089
#define IDM_HELP_CONTENTS               40090
#define IDM_TYPEVIEW_LOCATE             40090
#define IDM_TYPEVIEW_HEX2               40092
#define IDM_TYPEVIEW_DEC                40093
#define IDM_TYPEVIEW_OCT                40094
#define IDM_TYPEVIEW_BIGEND             40095
#define IDM_TYPEVIEW_UNSIGNED           40096
#define IDM_TYPEVIEW_BIGENDIAN          40097
#define IDM_TYPEVIEW_ALIGNNONE          40098
#define IDM_TYPEVIEW_ALIGNDWORD         40099
#define IDM_TYPEVIEW_ALIGNQWORD         40100
#define IDM_NEXT_WINDOW                 40101
#define IDM_                            40101
#define IDM_SUPERCALC_BASE              40102
#define IDM_VALUE_SIGNED                40102
#define IDM_TOGGLEDOCK                  40103
#define IDM_VALUE_ENDIAN                40103
#define IDM_VALUE_HEX                   40104
#define IDM_VALUE_8BIT                  40105
#define IDM_VALUE_BYTE                  40105
#define IDM_VALUE_16BIT                 40106
#define IDM_VALUE_WORD                  40106
#define IDM_VALUE_DWORD                 40107
#define IDM_VALUE_64BIT                 40108
#define IDM_VALUE_QWORD                 40108
#define IDM_VALUE_FLOAT                 40109
#define IDM_VALUE_DOUBLE                40110
#define IDM_TYPEVIEW_SAVE               40110
#define IDM_VALUE_SHOW                  40110
#define IDM_TYPEVIEW_PIN                40111
#define IDM_STATUS_HEX                  40111
#define IDM_TYPEVIEW_BACK               40112
#define IDM_STATUS_DEC                  40112
#define IDM_TYPEVIEW_FORW               40113
#define IDM_STATUSBAR_CURSORPOS         40113
#define IDM_TYPEVIEW_ALLTYPES           40114
#define IDM_STATUSBAR_SIZE              40115
#define IDM_STATUSBAR_VALUE             40116
#define IDM_STATUSBAR_MODE              40117
#define IDM_STATUSBAR_INSERT            40118
#define IDM_STATUSBAR_OVERWRITE         40119
#define IDM_STATUSBAR_READONLY          40120
#define IDM_TOOLS_CRC                   40122
#define IDM_TOOLS_CHECKSUM              40122
#define IDM_TOOLS_STRINGS               40123
#define IDM_TOOLS_COMPARE               40124
#define ID_VIEW_TOOLBAR40125            40125
#define IDM_VIEW_TOOLBAR                40126
#define ID_ACCELERATOR40128             40128
#define ID_VIEW_FITTOWINDOW             40129
#define IDM_VIEW_FITTOWINDOW            40130

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         40131
#define _APS_NEXT_CONTROL_VALUE         1049
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
